# **15 September 2023**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
path_property = 'https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/property_data.csv'
path_obes = '/Users/melawai.it/Documents/Work/Hacktiv8/PYTN-KS17/Sesi 6/obes.xls'
path_opsd = 'https://raw.githubusercontent.com/ardhiraka/PFDS_sources/master/opsd_germany_daily.csv'

### **Dataframe pertama**

In [ ]:
data1 = pd.read_csv(path_property)

data1.head(10)

           PID  ST_NUM     ST_NAME OWN_OCCUPIED NUM_BEDROOMS NUM_BATH SQ_FT
0  100001000.0   104.0      PUTNAM            Y            3        1  1000
1  100002000.0   197.0   LEXINGTON            N            3      1.5    --
2  100003000.0     NaN   LEXINGTON            N          NaN        1   850
3  100004000.0   201.0    BERKELEY           12            1      NaN   700
4          NaN   203.0    BERKELEY            Y            3        2  1600
5  100006000.0   207.0    BERKELEY            Y          NaN        1   800
6  100007000.0     NaN  WASHINGTON          NaN            2   HURLEY   950
7  100008000.0   213.0     TREMONT            Y           --        1   NaN
8  100009000.0   215.0     TREMONT            Y           na        2  1800

**Standar Missing Values**
  
    merupakan missing value yang bisa dideteksi oleh pandas. Tipe ini akan berisikan data NaN/NA.

In [ ]:
# Menggunakan isnull()

# Cek missing value di kolom st_num
data1["ST_NUM"].isnull()  # Apabila jawaban True maka terdapat missing value pada baris tersebut

# Apabila ingin mengecek secara keseluruhan
data1.isnull()

     PID  ST_NUM  ST_NAME  OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH  SQ_FT
0  False   False    False         False         False     False  False
1  False   False    False         False         False     False  False
2  False    True    False         False          True     False  False
3  False   False    False         False         False      True  False
4   True   False    False         False         False     False  False
5  False   False    False         False          True     False  False
6  False    True    False          True         False     False  False
7  False   False    False         False         False     False   True
8  False   False    False         False         False     False  False

In [ ]:
data1.info()


# Berdasarkan info di bawah ini, kolom num_bedroom dan num_bath seharusnya bertipe integer. Sedangkan sq_ft bertipe float.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PID           8 non-null      float64
 1   ST_NUM        7 non-null      float64
 2   ST_NAME       9 non-null      object
 3   OWN_OCCUPIED  8 non-null      object
 4   NUM_BEDROOMS  7 non-null      object
 5   NUM_BATH      8 non-null      object
 6   SQ_FT         8 non-null      object
dtypes: float64(2), object(5)
memory usage: 632.0+ bytes

**Non-Standart Missing Values**

  merupakan missing value dimana nilainya selain Nan/NA. seperti:


*  na, n/a, NA, NAN
*  ---, ..., dst


Cara menetapkan missing values pada suatu dataframe dapat dilakukan menguunakan parameter pandas yaitu na_values = .... .

In [ ]:
# Untuk mempermudah mengecek missing values. Kita kumpulkan terlebih dahulu nilai dari missing values tersebut.

miss_values =["n/a", "na", "--", "HURLEY"]

In [ ]:
# Menetapkan missing values pada
data1= pd.read_csv(path_property, na_values =miss_values)

data1.head(10)

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.0,PUTNAM,Y,3.0,1.0,1000.0
1,100002000.0,197.0,LEXINGTON,N,3.0,1.5,NaN
2,100003000.0,NaN,LEXINGTON,N,NaN,1.0,850.0
3,100004000.0,201.0,BERKELEY,12,1.0,NaN,700.0
4,NaN,203.0,BERKELEY,Y,3.0,2.0,1600.0
5,100006000.0,207.0,BERKELEY,Y,NaN,1.0,800.0
6,100007000.0,NaN,WASHINGTON,NaN,2.0,NaN,950.0
7,100008000.0,213.0,TREMONT,Y,NaN,1.0,NaN
8,100009000.0,215.0,TREMONT,Y,NaN,2.0,1800.0

In [ ]:
data1.isnull().head(10)

# Sekarang, setiap nilai yang termasuk ke dalam missing values akan otomatis terdeteksi sebagai missing values oleh pandas

     PID  ST_NUM  ST_NAME  OWN_OCCUPIED  NUM_BEDROOMS  NUM_BATH  SQ_FT
0  False   False    False         False         False     False  False
1  False   False    False         False         False     False   True
2  False    True    False         False          True     False  False
3  False   False    False         False         False      True  False
4   True   False    False         False         False     False  False
5  False   False    False         False          True     False  False
6  False    True    False          True         False      True  False
7  False   False    False         False          True     False   True
8  False   False    False         False          True     False  False

**Unexpected Missing Values**

  merupakan missing values yang diakibatkan oleh nilai yang tidak terduga seperti pada kolom own_occupied dan num_bath dimana muncul angka 12 dan HURLEY yang berbeda tipe dengan nilai lainnya. Oleh karena itu, pengecekkan missing value bisa dilakukan menggunakan

  **try ................... except ValueError**

**Kolom OWN_OCCUPIED**

In [ ]:
# Cek pada kolom own_occupied

count = 0
for row in data1["OWN_OCCUPIED"]:
  try:
    int(row)
    data1.loc[count,"OWN_OCCUPIED"] =np.nan   # np.nan dirubah menjadi missing value
  except ValueError:
    pass
    count+=1

data1

# Sekarang missing value pada kolom OWN_OCCUPIED sudah dirubah dalam bentuk NAN

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.0,PUTNAM,Y,3.0,1.0,1000.0
1,100002000.0,197.0,LEXINGTON,N,3.0,1.5,NaN
2,100003000.0,NaN,LEXINGTON,N,NaN,1.0,850.0
3,100004000.0,201.0,BERKELEY,NaN,1.0,NaN,700.0
4,NaN,203.0,BERKELEY,Y,3.0,2.0,1600.0
5,100006000.0,207.0,BERKELEY,Y,NaN,1.0,800.0
6,100007000.0,NaN,WASHINGTON,NaN,2.0,NaN,950.0
7,100008000.0,213.0,TREMONT,Y,NaN,1.0,NaN
8,100009000.0,215.0,TREMONT,Y,NaN,2.0,1800.0

In [ ]:
# Merubah tipe data pada kolom "OWN_OCCUPIED" ke dalam categorical

type= pd.CategoricalDtype(categories=['N', 'Y'], ordered=True)

data1["OWN_OCCUPIED"]= data1["OWN_OCCUPIED"].astype(type)

data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PID           8 non-null      float64
 1   ST_NUM        7 non-null      float64
 2   ST_NAME       9 non-null      object
 3   OWN_OCCUPIED  7 non-null      category
 4   NUM_BEDROOMS  5 non-null      float64
 5   NUM_BATH      7 non-null      float64
 6   SQ_FT         7 non-null      float64
dtypes: category(1), float64(5), object(1)
memory usage: 693.0+ bytes

In [ ]:
# Cari modus dari kolom "OWN_OCCUPIED"
modus = data1["OWN_OCCUPIED"].mode()
modus

# Berdasarkan hasil di atas dapat disimpulkan bahwa modus adalah "Y". Sehingga, missing value akan diisi dengan "Y"

0    Y
Name: OWN_OCCUPIED, dtype: category
Categories (2, object): ['N' < 'Y']

In [ ]:
# Mereplace missing value dengan modus

data1["OWN_OCCUPIED"].fillna("Y", inplace= True)

data1

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.0,PUTNAM,Y,3.0,1.0,1000.0
1,100002000.0,197.0,LEXINGTON,N,3.0,1.5,NaN
2,100003000.0,NaN,LEXINGTON,N,NaN,1.0,850.0
3,100004000.0,201.0,BERKELEY,Y,1.0,NaN,700.0
4,NaN,203.0,BERKELEY,Y,3.0,2.0,1600.0
5,100006000.0,207.0,BERKELEY,Y,NaN,1.0,800.0
6,100007000.0,NaN,WASHINGTON,Y,2.0,NaN,950.0
7,100008000.0,213.0,TREMONT,Y,NaN,1.0,NaN
8,100009000.0,215.0,TREMONT,Y,NaN,2.0,1800.0

**KOLOM NUM_BEDROOMS**

In [ ]:
# Mencari mean untuk mengisi missing value

data1["NUM_BEDROOMS"].mean()

# hasilnya 2.4

2.4

In [ ]:
# Masukkan mean ke dalam kolom

data1["NUM_BEDROOMS"].fillna(2.4, inplace=True)
data1

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.0,PUTNAM,Y,3.0,1.0,1000.0
1,100002000.0,197.0,LEXINGTON,N,3.0,1.5,NaN
2,100003000.0,NaN,LEXINGTON,N,2.4,1.0,850.0
3,100004000.0,201.0,BERKELEY,Y,1.0,NaN,700.0
4,NaN,203.0,BERKELEY,Y,3.0,2.0,1600.0
5,100006000.0,207.0,BERKELEY,Y,2.4,1.0,800.0
6,100007000.0,NaN,WASHINGTON,Y,2.0,NaN,950.0
7,100008000.0,213.0,TREMONT,Y,2.4,1.0,NaN
8,100009000.0,215.0,TREMONT,Y,2.4,2.0,1800.0

In [ ]:
# Ubah tipe data " NUM_BEDROOMS" ke dalam int

data1["NUM_BEDROOMS"] = data1["NUM_BEDROOMS"].astype("int")
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PID           8 non-null      float64
 1   ST_NUM        7 non-null      float64
 2   ST_NAME       9 non-null      object
 3   OWN_OCCUPIED  9 non-null      category
 4   NUM_BEDROOMS  9 non-null      int64
 5   NUM_BATH      7 non-null      float64
 6   SQ_FT         7 non-null      float64
dtypes: category(1), float64(4), int64(1), object(1)
memory usage: 693.0+ bytes

**KOLOM NUM_BATH**

In [ ]:
# Cara mengetahui missing value pada kolom num_bath
data1[data1["NUM_BATH"].astype("float")]  # Di cek menggunakan float karena ada data yang float

# Setelah dirun ternyata pada kolom num_bath terdapat srting "HURLEY" maka "HURLEY" diubah dulu. Dengan menambahkan "HURLEY" dalam missing value

KeyError: ignored

In [ ]:
# Isikan missing value dengan median dari kolom

data1["NUM_BATH"].median()

1.0

In [ ]:
data1["NUM_BATH"].fillna(1, inplace=True)
data1

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.0,PUTNAM,Y,3,1.0,1000.0
1,100002000.0,197.0,LEXINGTON,N,3,1.5,NaN
2,100003000.0,NaN,LEXINGTON,N,2,1.0,850.0
3,100004000.0,201.0,BERKELEY,Y,1,1.0,700.0
4,NaN,203.0,BERKELEY,Y,3,2.0,1600.0
5,100006000.0,207.0,BERKELEY,Y,2,1.0,800.0
6,100007000.0,NaN,WASHINGTON,Y,2,1.0,950.0
7,100008000.0,213.0,TREMONT,Y,2,1.0,NaN
8,100009000.0,215.0,TREMONT,Y,2,2.0,1800.0

In [ ]:
# Bagian NUM_BATH harus int. Sehingga, ganti terlebih dahulu nilai float ke int dengan membulatkan ke atas menggunakan try except.
data1["NUM_BATH"] = data1["NUM_BATH"].astype("int")

data1

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.0,PUTNAM,Y,3,1,1000.0
1,100002000.0,197.0,LEXINGTON,N,3,1,NaN
2,100003000.0,NaN,LEXINGTON,N,2,1,850.0
3,100004000.0,201.0,BERKELEY,Y,1,1,700.0
4,NaN,203.0,BERKELEY,Y,3,2,1600.0
5,100006000.0,207.0,BERKELEY,Y,2,1,800.0
6,100007000.0,NaN,WASHINGTON,Y,2,1,950.0
7,100008000.0,213.0,TREMONT,Y,2,1,NaN
8,100009000.0,215.0,TREMONT,Y,2,2,1800.0

**KOLOM PID, ST_NUM, dan "SQ_FT"**

In [ ]:
# Isi missing value pada PID

data1["PID"].fillna(100005000.0, inplace=True)

data1

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.0,PUTNAM,Y,3,1,1000.0
1,100002000.0,197.0,LEXINGTON,N,3,1,1100.0
2,100003000.0,NaN,LEXINGTON,N,2,1,850.0
3,100004000.0,201.0,BERKELEY,Y,1,1,700.0
4,100005000.0,203.0,BERKELEY,Y,3,2,1600.0
5,100006000.0,207.0,BERKELEY,Y,2,1,800.0
6,100007000.0,NaN,WASHINGTON,Y,2,1,950.0
7,100008000.0,213.0,TREMONT,Y,2,1,1100.0
8,100009000.0,215.0,TREMONT,Y,2,2,1800.0

In [ ]:
# Isi missing value pada kolom "ST_NUM"
mean =data1["ST_NUM"].mean()

data1["ST_NUM"].fillna(mean, inplace=True)

data1

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.000000,PUTNAM,Y,3,1,1000.0
1,100002000.0,197.000000,LEXINGTON,N,3,1,1100.0
2,100003000.0,191.428571,LEXINGTON,N,2,1,850.0
3,100004000.0,201.000000,BERKELEY,Y,1,1,700.0
4,100005000.0,203.000000,BERKELEY,Y,3,2,1600.0
5,100006000.0,207.000000,BERKELEY,Y,2,1,800.0
6,100007000.0,191.428571,WASHINGTON,Y,2,1,950.0
7,100008000.0,213.000000,TREMONT,Y,2,1,1100.0
8,100009000.0,215.000000,TREMONT,Y,2,2,1800.0

In [ ]:
# isi missing value pada kolom ini dengan mean dari data

mean =data1["SQ_FT"].mean()

data1["SQ_FT"].fillna(mean, inplace=True)

data1

,PID,ST_NUM,ST_NAME,OWN_OCCUPIED,NUM_BEDROOMS,NUM_BATH,SQ_FT
0,100001000.0,104.000000,PUTNAM,Y,3,1,1000.0
1,100002000.0,197.000000,LEXINGTON,N,3,1,1100.0
2,100003000.0,191.428571,LEXINGTON,N,2,1,850.0
3,100004000.0,201.000000,BERKELEY,Y,1,1,700.0
4,100005000.0,203.000000,BERKELEY,Y,3,2,1600.0
5,100006000.0,207.000000,BERKELEY,Y,2,1,800.0
6,100007000.0,191.428571,WASHINGTON,Y,2,1,950.0
7,100008000.0,213.000000,TREMONT,Y,2,1,1100.0
8,100009000.0,215.000000,TREMONT,Y,2,2,1800.0